name = "fairgemeinschaft-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "fairgemeinschaft-db"
database_id = "e2c25aba-350a-4f67-a191-89f4da1d79d9"

[vars]
APP_ORIGIN = "https://dpolz.github.io"
