name = "fairgemeinschaft-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Nach dem Ausführen von `npx wrangler d1 create fairgemeinschaft-db` die generierte database_id hier eintragen:
[[d1_databases]]
binding = "fairgemeinschaft_db"
database_name = "fairgemeinschaft-db"
database_id = "e2c25aba-350a-4f67-a191-89f4da1d79d9"

[vars]
APP_ORIGIN = "https://dpolz.github.io"
